services:
  app:
    build:
      context: ./portfolio_back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/portfolio
      SPRING_DATASOURCE_USERNAME: db_user_iscod
      SPRING_DATASOURCE_PASSWORD: db_password_iscod
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: db_user_iscod
      POSTGRES_PASSWORD: db_password_iscod
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./portfolio_front
      dockerfile: Dockerfile
    ports:
      - "3000:80"