events { }

http {
    server {
        listen 80;
        server_name allanperez.fr www.allanperez.fr api.allanperez.fr;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name allanperez.fr www.allanperez.fr;

        ssl_certificate     /etc/nginx/certs/allanperez.fr/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/allanperez.fr/key.pem;

        location / {
            proxy_pass http://frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 443 ssl;
        server_name api.allanperez.fr;

        ssl_certificate     /etc/nginx/certs/api.allanperez.fr/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/api.allanperez.fr/key.pem;

        location / {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
